### ISSUE TITLE
BT-2 Support

### ISSUE THREAD

**Issue by matthewcobb** [cyrils/web-bt1#3]
Great project! I saw your python lib supported the BT-2 protocols. I am setting this up on a raspberry pi and would like to report my battery status to an Electron app. This web based API is a lot more convenient for that. Is there support for BT-2 here as well? 

Many thanks!

**Comment by cyrils** [comment]
Apparently yes. Both BT-1 and BT-2 use same protocol, and this code will work seamlessly for charge controllers. But if you are trying to read smart battery then the registers and values are different. You have to look into `BatteryClient.py`.

**Comment by matthewcobb** [comment]
Thank you for the fast reply, I will test it out 🙏
